[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "fichero-consumo-adaptado"
version = "0.1.0"
dependencies = [
    "pandas",
    "clickhouse-connect",
    "pytest",
]

[tool.setuptools.packages.find]
where = ["src"]
